--table creation query--

create table TRADE_STORE(
	ID integer auto_increment primary key,
	TRADE_ID varchar(5) NOT NULL,
	VERSION number(2,0) NOT NULL,
	COUNTER_PARTY_ID varchar(5) NOT NULL,
	BOOK_ID varchar(5) NOT NULL,
	MATURITY_DATE date NOT NULL,
	CREATED_DATE date NOT NULL,
	EXPIRED varchar(5) NOT NULL 
	

);



--insertion in table---
insert into TRADE_STORE(TRADE_ID,VERSION,COUNTER_PARTY_ID,BOOK_ID,MATURITY_DATE,CREATED_DATE,EXPIRED) values('T1',1,'CP-1','B1','2020-05-20',CURRENT_DATE(),'N');

insert into TRADE_STORE(TRADE_ID,VERSION,COUNTER_PARTY_ID,BOOK_ID,MATURITY_DATE,CREATED_DATE,EXPIRED) values('T2',2,'CP-2','B1','2021-05-20',CURRENT_DATE(),'N');

insert into TRADE_STORE(TRADE_ID,VERSION,COUNTER_PARTY_ID,BOOK_ID,MATURITY_DATE,CREATED_DATE,EXPIRED) values('T2',1,'CP-1','B1','2021-05-20','2015-03-14','N');

insert into TRADE_STORE(TRADE_ID,VERSION,COUNTER_PARTY_ID,BOOK_ID,MATURITY_DATE,CREATED_DATE,EXPIRED) values('T3',3,'CP-3','B2','2014-05-20',CURRENT_DATE(),'Y');